run:
  learning_rate: 0.
  state_variables: null
  simulation_time: null
isolate:
  exc_stim: True
  inh_stim: True
  stim_count: 1000
  strength: weak
stimulus: null
name: perturbation
save_matrix: False
init_matrix : null