run:
  learning_rate : 0.
  simulation_time : full
  state_variables : null
  save_weights : False
  chunk_size : 10
stimulus :
  num_indices : 10
  spacing : 1
folder : lognormal
init_matrix : null
name : stimulus100ms