run:
  learning_rate : 0.
  simulation_time : 1010
  state_variables : null
  save_weights : False
  chunk_size : 10
stimulus : data/stimuli/frac10pc1000stim.pkl
folder : lognormal
init_matrix : null
name : stimulus100ms