neuron :
  alpha1 : True
  alpha2 : 0.3
  reset_potential : True
  tau_stdp_ms : 20
  plasticity : hebb
  plast_ii : True
  recharge : 0
background:
  background_poisson : 2
  poisson_amplitude : 0.3
target_rate : 3
prefix : lognorm
folder : sp1
name : hebb_ii