neuron :
  alpha1 : True
  alpha2 : 0.3
  reset_potential : True
  tau_stdp_ms : 20
  plasticity : hebb
  recharge : 1.
background:
  background_poisson : 2
  poisson_amplitude : 0.3
target_rate : 1.8
prefix : lognorm
folder : sp1
name : hebb_recharge_plus_strong_tr1.8